apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addon-nginx-ingress
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: git@github.com:felipelaptrin/cloud-agnostic-k8s.git
    targetRevision: feat/argocd
    path: argocd/local
