apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: PreSync
spec:
  project: default
  destination:
    name: in-cluster
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: postgres-operator
    repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    targetRevision: 1.12.2
    helm:
      valuesObject:
        configKubernetes:
          enable_cross_namespace_secret: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: PreSync
spec:
  project: default
  destination:
    name: in-cluster
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: postgres-operator-ui
    repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
    targetRevision: 1.12.2
    helm:
      valuesObject:
        envs:
          targetNamespace: "*"
